# Compiler
CC = gcc

# Compiler Flags
CFLAGS = -Wall -g

# Target executable
TARGET = MLFQ

# Source files
SRCS = MLFQ.c job.c queue.c

# Header files
HDRS = job.h queue.h

# Object files
OBJS = $(SRCS:.c=.o)

# Default target
all: $(TARGET)

# Build target executable
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

# Compile .c files to .o files
%.o: %.c $(HDRS)
	$(CC) $(CFLAGS) -c $< -o $@

# Clean up build files
clean:
	rm -f $(OBJS) $(TARGET) output.txt output2.txt
