CC = gcc
CFLAGS = -Wall -g

EXECS = RR MLFQ SRTF

RR_SRCS = RR.c job.c queue.c
MLFQ_SRCS = MLFQ.c job.c queue.c
SRTF_SRCS = SRTF.c job.c queue.c

all: $(EXECS)

RR: $(RR_SRCS)
	$(CC) $(CFLAGS) -o RR $(RR_SRCS)

MLFQ: $(MLFQ_SRCS)
	$(CC) $(CFLAGS) -o MLFQ $(MLFQ_SRCS)

SRTF: $(SRTF_SRCS)
	$(CC) $(CFLAGS) -o SRTF $(SRTF_SRCS)

test: all
	./RR job1.txt > RR_output1.txt
	./RR job2.txt > RR_output2.txt
	./MLFQ job1.txt > MLFQ_output1.txt
	./MLFQ job2.txt > MLFQ_output2.txt
	./SRTF job1.txt > SRTF_output1.txt
	./SRTF job2.txt > SRTF_output2.txt
	echo "Tests completed. Check output files."

clean:
	rm -f $(EXECS) *.o *.txt
